plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメントを不要にする
Style/Documentation:
  Enabled: false

# 長い行を許可
Layout/LineLength:
  Max: 120

# ブロックの行数制限を緩和
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'