
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: motivation_streaming_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"  # ← ここを修正 ✅
    volumes:
      - .:/motivation-streaming-app
      - bundle_data:/usr/local/bundle
      - node_modules:/motivation-streaming-app/node_modules  # ← これを追加 ✅
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome  # Chrome コンテナへの依存を追加
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub  # Chrome コンテナの URL を追加
    stdin_open: true
    tty: true

  chrome:  # Chrome コンテナを追加
    image: selenium/standalone-chrome:124.0
    ports:
      - "4444:4444"


volumes:
  postgres_data:
  bundle_data:
  node_modules:  # ← これを追加 ✅